# Generated by Django 6.0.1 on 2026-01-24 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_gpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gpa', models.FloatField()),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('username', models.CharField(max_length=250, unique=True)),
                ('level', models.IntegerField(null=True)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.employee'),
        ),
        migrations.CreateModel(
            name='EmployeePrjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employees', models.ManyToManyField(through='students.EmployeePrjects', to='students.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employeeprjects',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.project'),
        ),
    ]
