# Generated by Django 6.0.1 on 2026-01-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_employee_department_manager_employeeprjects_project_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='Department',
        ),
    ]
