# Generated by Django 6.0.1 on 2026-01-24 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_department_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='Employee',
        ),
    ]
