# Generated by Django 6.0.1 on 2026-01-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_employee_table'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('gpa__lte', 4), ('gpa__gt', 0)), name='check_valie_gpa'),
        ),
    ]
