# Generated by Django 6.0.1 on 2026-01-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_employee_check_valie_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
