# Generated by Django 6.0.2 on 2026-02-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs'),
        ),
    ]
