# Generated by Django 6.0.2 on 2026-02-13 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_product_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cv',
        ),
    ]
