# Generated by Django 5.2.10 on 2026-01-24 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gpa', models.FloatField()),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('level', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'Emploee',
            },
        ),
        migrations.CreateModel(
            name='EmployeeProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('gpa__lte', 4), ('gpa__gt', 0)), name='check_valie_gpa'),
        ),
        migrations.AlterModelTable(
            name='department',
            table='Department',
        ),
        migrations.AddField(
            model_name='employee',
            name='dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.department'),
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.employee'),
        ),
        migrations.AddField(
            model_name='employeeprojects',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.employee'),
        ),
        migrations.AddField(
            model_name='project',
            name='employee',
            field=models.ManyToManyField(through='students.EmployeeProjects', to='students.employee'),
        ),
        migrations.AddField(
            model_name='employeeprojects',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.project'),
        ),
    ]
